#!/usr/bin/ruby

Directory="/home/aaf/e-yo"
require "#{Directory}/xml_parser.rb"
require "#{Directory}/cal.rb"
require "#{Directory}/gui_gtk.rb"


class MainApp
	def initialize(configfile) 
		# Here we will load the config file
		config = Config.new(configfile)
	end	
end

ConfigFile="#{Directory}/conf_gui.xml"

CALENDAR_FILE = "#{Directory}/Calendar.aux.csv"
c1 = Calendar.new(CALENDAR_FILE)
c1.sort
c1.test_doubled_values
Today = [Time.now.year,"%02d" % Time.now.month,"%02d" % Time.now.day].join('')
sintrom_today = c1.sintrom_amount(Today)
next_test = c1.next_sintrom_test(Today),"\n" 
next_update = c1.sintrom_next_update,"\n" 


init
app = Win.new( "e-yo")
app.msg_area_change("Sintrom","Today's amount of Sintrom: #{sintrom_today}","Next test should take place on #{next_test}","The file should be updated before #{next_update}")
main
